AWSTemplateFormatVersion: '2010-09-09'
Description: BirdTag System S3 and DynamoDB resources

Resources:
  BirdBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: birdtag-models-fit5225-g138

  BirdDbTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: bird-db
      AttributeDefinitions:
        - AttributeName: media_id
          AttributeType: S
        - AttributeName: bird_tag
          AttributeType: S
        - AttributeName: thumb_url
          AttributeType: S
        - AttributeName: full_url
          AttributeType: S
      KeySchema:
        - AttributeName: media_id
          KeyType: HASH
        - AttributeName: bird_tag
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: bird_tag-index
          KeySchema:
            - AttributeName: bird_tag
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: thumb_url-index
          KeySchema:
            - AttributeName: thumb_url
              KeyType: HASH
          Projection:
            ProjectionType: INCLUDE
          NonKeyAttributes:
            - bird_tag
            - file_type
            - full_url
        - IndexName: full_url-index
          KeySchema:
            - AttributeName: full_url
              KeyType: HASH
          Projection:
            ProjectionType: INCLUDE
          NonKeyAttributes:
            - bird_tag
            - file_type
            - thumb_url

  Resources:
    ImageRepo:
      Type: AWS::ECR::Repository
      Properties:
        RepositoryName: Page/image-repo

    VideoRepo:
      Type: AWS::ECR::Repository
      Properties:
        RepositoryName: Page/video-repo

    AudioRepo:
      Type: AWS::ECR::Repository
      Properties:
        RepositoryName: Page/audio-repo

Outputs:
  BucketName:
    Description: "S3 Bucket Name"
    Value: !Ref BirdBucket
  DynamoDBTableName:
    Description: "DynamoDB Table Name"
    Value: !Ref BirdDbTable
  ImageRepoURI:
    Description: "ECR URI for image repository"
    Value: !GetAtt ImageRepo.RepositoryUri
  VideoRepoURI:
    Description: "ECR URI for video repository"
    Value: !GetAtt VideoRepo.RepositoryUri
  AudioRepoURI:
    Description: "ECR URI for audio repository"
    Value: !GetAtt AudioRepo.RepositoryUri
